### ISSUE TITLE
allow for new 2k payload limit for iOS 8

### ISSUE THREAD

**Issue by chrisvaughn** [freshplanet/AppEngine-SocketPool#2]
According to https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html#//apple_ref/doc/uid/TP40008194-CH100-SW1

iOS 8 and later can except payloads up to 2 kilobytes. It would nice to be able to send large payloads to devices that support it.

**Comment by AlexisH** [comment]
Thanks for noticing this, will definitely update the limit

Alexis
